### ISSUE TITLE
tooltip is on icon instead of button

### ISSUE THREAD

**Issue by lorennorman** [codeTao42/little_by_little#7]
/cc @codeTao42

**Comment by codeTao42** [comment]
This issue should be fixed by my latest branch. inspect when you have the time and  we will merge it if you think the issue is appropriately handled.

**Comment by lorennorman** [comment]
See? ^^^ The PR now appears here in the issue due to the mention. You can also mention in the other direction with the ID of the PR, like this: Fixed by #8
